### ISSUE TITLE
Concerns Regarding Shared Puzzle Solutions

### ISSUE THREAD

**Issue by ght-marklin** [aflr/CodinGame#1]
I hope this message finds you well. I recently noticed that you shared a solution to a coding puzzle on your GitHub repository. While I appreciate your enthusiasm for solving puzzles, I wanted to express some concerns.

The puzzle in question is part of an online test that we use for assessing candidates. Sharing solutions publicly can have unintended consequences. It not only takes away the joy and challenge for others attempting the puzzle but also compromises the integrity of our assessment process.

Additionally, we've observed instances where candidates have copied and pasted solutions, impacting the authenticity of their responses. This is a concern for us as it undermines the purpose of the assessment, which is to evaluate individual problem-solving skills.

I understand that everyone enjoys a good puzzle, but I kindly request that you refrain from sharing solutions publicly. This ensures a fair and level playing field for all candidates and preserves the integrity of our assessment process.

Thank you for your understanding and cooperation in this matter. If you have any questions or concerns, feel free to reach out.

**Comment by aflr** [comment]
Hello Mark @ght-marklin. I understand your concern and would like to help. 

I was under the impression that posting solutions to single player puzzles would be fine, and that's why I was careful not to post my solutions to the competitive gamemodes like code golf, optimization, bot programming, or clash of code.

Is there any specific puzzle (or puzzles) you would want removed? Is there any kind of puzzle solution that is okay to share? Is there any way to make sharing these solutions not compromise the integrity of the assessment processes?

Thanks for your time!

**Comment by ght-marklin** [comment]
Hi AFLR,

Thank you for your understanding and cooperation!

Regarding the puzzle solution to be removed, I would like to request the removal of "Boggle with Friends" if possible. This is the puzzle I selected for a candidate last week from the latest puzzles, and I believe its solution has a lower chance of being exposed on the internet.

Once again, thank you for your prompt attention to this matter.

**Comment by aflr** [comment]
Hello Mark,

I have now removed my solution to the puzzle "Boggle with friends", both from the repository and from the commit history, so it is impossible to find.

Have a good day!
